version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "IMAGE_TAG IS" $IMAGE_TAG	
  build:
    commands:
      - docker build -t mynoodles-repo .
      - docker tag mynoodles-repo:latest $REPOSITORY:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY:$IMAGE_TAG
#      - printf '{"Image":"%s:%s"}' $REPOSITORY $IMAGE_TAG > build.json
      - printf '[{"name":"noodles-container-automated","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > build.json
artifacts:
  files:
    - build.json
  discard-paths: yes