version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
      - TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - printf "%s" $TAG	
  build:
    commands:
      - docker build -t mynoodles-repo .
      - docker tag mynoodles-repo:latest $REPOSITORY:$TAG
  post_build:
    commands:
      - docker push ${REPOSITORY}:${TAG}
      - printf '{"Image":"%s:%s"}' $RESPOSITORY $TAG > build.json
artifacts:
  files:
    - build.json
  discard-paths: yes
